ARG BASE_IMAGE
FROM $BASE_IMAGE
# FROM ubuntu:22.04
LABEL maintainer="your-email@example.com"
LABEL version="1.0"
LABEL description="Basic Ubuntu Docker image with common tools"
# ARG USER_NAME         = rk
# ARG LUBANCAT_DIR      = $USER_NAME/lubancat
# ARG LUBANCAT_SDK_DIR  = /root/lubancat_sdk
# ARG IMAGES_DIR        = /root/images
ARG USER_NAME=rk
ARG LUBANCAT_DIR=/home/$USER_NAME/lubancat
ARG LUBANCAT_SDK_DIR=/home/$USER_NAME/lubancat_sdk
ARG LUBANCAT_DATA_DIR=/home/$USER_NAME/data
ARG IMAGES_DIR=/root/images
COPY shell/setup.sh .
COPY shell/entrypoint.sh /
RUN chmod 777 /entrypoint.sh
# if chomd +x .sh, permission's error will occur
# 设置环境变量，避免交互式配置提示
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
ARG USER_ID=1000
ARG GROUP_ID=1000
# 设置时区
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 更新包管理器并安装基础工具
RUN apt-get update && \
    apt-get install -y \
    curl \
    wget \
    vim \
    git \
    unzip \
    sudo \
    tzdata \
    ca-certificates \
    software-properties-common \
    gnupg \
    lsb-release \
    # 语言支持
    locales
    # 清理缓存以减小镜像大小
RUN bash setup.sh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/ /tmp/* /var/tmp/*
# 创建与本地用户相同UID/GID的用户组和用户
RUN groupadd -g ${GROUP_ID}  $USER_NAME && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} -s /bin/bash $USER_NAME && \
    echo "$USER_NAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
# checkout to non-root user
USER $USER_NAME
RUN mkdir -p $LUBANCAT_SDK_DIR $LUBANCAT_DATA_DIR
# add sdk to image
ADD SDK/LubanCat_Linux_Generic_SDK_20250628.tgz $LUBANCAT_DATA_DIR
RUN cd $LUBANCAT_DATA_DIR \
    # && tar xf LubanCat_Linux_Generic_SDK_20250628.tgz
    # && .repo/repo/repo sync -c -j8
    && git config --global --add safe.directory '*' \
    && chown -R rk:rk . \
    && .repo/repo/repo sync -c -j8

WORKDIR /home/$USER_NAME
# RUN touch test.txt
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
